### ISSUE TITLE
Error: No module named 'asyncore'

### ISSUE THREAD

**Issue by flyibeat** [Blear/HassLife#8]
asyncore在Python3.12中被移除
![1](https://github.com/Blear/HassLife/assets/78073839/28182236-c394-4351-a5dd-08cdb7c36dcb)

log
日志: homeassistant.setup
来源: setup.py:296
首次发生: 09:49:26 (1 全部发生)
上次记录: 09:49:26

Setup failed for custom integration 'hasslife': Unable to import component: No module named 'asyncore'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 296, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 894, in async_get_component
    comp = self.get_component()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 921, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/hasslife/__init__.py", line 11, in <module>
    from .molo_client_app import MOLO_CLIENT_APP
  File "/config/custom_components/hasslife/molo_client_app.py", line 2, in <module>
    import asyncore
ModuleNotFoundError: No module named 'asyncore'

**Comment by Blear** [comment]
你好，感谢反馈，插件已更新，请更新到2.0版本
